apiVersion: ignite.weave.works/v1alpha2
kind: VM
metadata:
  created: "2020-06-08T12:31:20Z"
  name: dark-glade
  uid: f53b6d04e98ecf56
spec:
  cpus: 1
  diskSize: 4GB
  image:
    oci: weaveworks/ignite-ubuntu:latest
  kernel:
    cmdLine: console=ttyS0 reboot=k panic=1 pci=off ip=dhcp
    oci: weaveworks/ignite-kernel:4.19.125
  memory: 512MB
  network: {}
  sandbox:
    oci: weaveworks/ignite:v0.7.0
  storage: {}
status:
  image:
    id: oci://docker.io/weaveworks/ignite-ubuntu@sha256:f8032a6738fdb372eb7e64734c9481f873b57e0ea72b610e0189f0a329283173
    size: 237539766B
  kernel:
    id: oci://docker.io/weaveworks/ignite-kernel@sha256:9f961af5a9735021682eed102f5b8b14c8ebc8273a5cc192779c0686f1241653
    size: 52178500B
  running: true
